server:
  port: 80
spring:
  application:
    name: consul-consumer-order
    #consul注册中心
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: localhost
      port: 8500