server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由。
      routes:
        - id: payment_routh #路由的ID，要求是唯一的
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service  #匹配后提供服务的地址
          predicates:
            - Path=/payment/lb/**
            #- After=2021-03-20T12:45:54.065+08:00[Asia/Shanghai] #在某个时间节点之后才可以使用
            #- Cookie=username,fhn
            #- Header=Request-id,\d+
            - Method=get
eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway-service
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
